// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW-5Ft2uaGcff8jMLQrbEDy2ykkhkhcrM',
    appId: '1:598313134756:ios:4e0e46492337e4cc2c1431',
    messagingSenderId: '598313134756',
    projectId: 'newsmm-1b73d',
    databaseURL: 'https://newsmm-1b73d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsmm-1b73d.firebasestorage.app',
    iosBundleId: 'com.example.newsappMm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6WUwDNt3RnGDqW77VIrzGCfD5rFK49r0',
    appId: '1:598313134756:web:37b59cd6963d74f72c1431',
    messagingSenderId: '598313134756',
    projectId: 'newsmm-1b73d',
    authDomain: 'newsmm-1b73d.firebaseapp.com',
    databaseURL: 'https://newsmm-1b73d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsmm-1b73d.firebasestorage.app',
    measurementId: 'G-G72NKEW490',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6WUwDNt3RnGDqW77VIrzGCfD5rFK49r0',
    appId: '1:598313134756:web:37b59cd6963d74f72c1431',
    messagingSenderId: '598313134756',
    projectId: 'newsmm-1b73d',
    authDomain: 'newsmm-1b73d.firebaseapp.com',
    databaseURL: 'https://newsmm-1b73d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsmm-1b73d.firebasestorage.app',
    measurementId: 'G-G72NKEW490',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW-5Ft2uaGcff8jMLQrbEDy2ykkhkhcrM',
    appId: '1:598313134756:ios:4e0e46492337e4cc2c1431',
    messagingSenderId: '598313134756',
    projectId: 'newsmm-1b73d',
    databaseURL: 'https://newsmm-1b73d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsmm-1b73d.firebasestorage.app',
    iosBundleId: 'com.example.newsappMm',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy5mioRi7uhB_zwVSj9jjt_cvvWnV9YoU',
    appId: '1:598313134756:android:754b5207598dbf612c1431',
    messagingSenderId: '598313134756',
    projectId: 'newsmm-1b73d',
    databaseURL: 'https://newsmm-1b73d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newsmm-1b73d.firebasestorage.app',
  );

}